include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - test
  - deploy

variables:
    BUNDLE: "gcolor3-nightly.flatpak"
    MANIFEST_PATH: "nl.hjdskes.gcolor3.json"
    FLATPAK_MODULE: "gcolor3"

flatpak:
  extends: '.flatpak'
  image: "registry.gitlab.gnome.org/gnome/gnome-runtime-images/rust_bundle:master"
  variables:
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    APP_ID: "nl.hjdskes.gcolor3"
