.TH GCOLOR3 "1" "August 26, 2018"
.
.SH NAME
gcolor3 \- a color selection dialog
.
.SH SYNOPSIS
.B gcolor3
.RI [ OPTIONS ]
.
.SH DESCRIPTION
.B gcolor3
enables you to pick the color from any pixel on your screen. It also offers a palette, so that you can easily mix and match a couple of colors together.
.
.SH OPTIONS
.SS "Help Options"
.TP
.BR \-h ", " \-\^\-help
Show help options
.TP
.BR \-\^\-help\-all
Show all help options
.SS "Application Options"
.TP
.BR \-v ", " \-\^\-version
Show the application's version
.TP
.BI "\-\^\-display=" DISPLAY
X display to use
.
.SH COPYRIGHT
Copyright 2013\(en2018 Jente Hidskes <hjdskes@gmail.com>
.PP
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
.
.SH BUGS
For any bugs or feature requests, please create an issue on GitHub at https://github.com/kjdskes/gcolor3/issues

